import t from '../localization';
import moment from 'moment';

const SHARED_FILTERS = {
  period: {
    type: 'period',
    dropDown: true,
    placeholder: 'Все',
  },
};

const FILTERS_LIST = {
  ...SHARED_FILTERS,
  toStartAtDateFrom: {
    title: t.order('filters.toStartAtDateFrom'),
    type: 'toStartAtDateFrom',
    placeholder: `от ${moment().format('ll')}`,
    datePicker: true,
    period: 1,
  },
  toStartAtDateTill: {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'toStartAtDateTill',
    datePicker: true,
    period: 2,
  },
  finishDateFrom: {
    title: t.order('filters.finishDateFrom.title'),
    label: t.order('filters.finishDateFrom.label'),
    placeholder: `от ${moment().format('ll')}`,
    type: 'finishDateFrom',
    datePicker: true,
  },
  finishDateTill: {
    title: t.order('filters.finishDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'finishDateTill',
    datePicker: true,
  },
  orderId: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'orderId',
    icon: 'searchBlue',
  },
  orderStatus: {
    title: t.order('filters.orderStatus.title'),
    label: t.order('filters.orderStatus.label'),
    placeholder: t.order('filters.orderStatus.placeholder'),
    type: 'orderStatuses',
    dropDownKey: 'transportOrderStatuses',
    dropDown: true,
  },
  orderStage: {
    title: t.order('filters.orderStage.title'),
    label: t.order('filters.orderStage.label'),
    placeholder: t.order('filters.orderStage.placeholder'),
    type: 'orderStage',
    dropDownKey: 'transportOrderStages',
    dropDown: true,
  },
  orderType: {
    title: t.order('filters.orderType.title'),
    placeholder: t.order('filters.orderType.placeholder'),
    label: t.order('filters.orderType.label'),
    type: 'orderType',
    dropDownKey: 'orderTypes',
    dropDown: true,
  },
  deliverAddress: {
    title: t.order('filters.deliverAddress.title'),
    placeholder: t.order('filters.deliverAddress.placeholder'),
    label: t.order('filters.deliverAddress.label'),
    type: 'deliverAddress',
  },
  loadingAddress: {
    title: t.order('filters.loadingAddress.title'),
    placeholder: t.order('filters.loadingAddress.placeholder'),
    label: t.order('filters.loadingAddress.label'),
    type: 'loadingAddress',
  },
  vehicleType: {
    title: t.order('filters.transportType.title'),
    placeholder: t.order('filters.transportType.placeholder'),
    label: t.order('filters.transportType.label'),
    type: 'vehicleType',
    dropDownKey: 'vehicleTypes',
    dropDown: true,
  },
  plateNumber: {
    title: t.order('filters.plateNumber.title'),
    placeholder: t.order('filters.plateNumber.placeholder'),
    label: t.order('filters.plateNumber.label'),
    type: 'plateNumber',
  },
  producerTitle: {
    title: t.order('filters.producerTitle.title'),
    placeholder: t.order('filters.producerTitle.placeholder'),
    label: t.order('filters.producerTitle.label'),
    type: 'producerTitle',
  },
  executorSurname: {
    title: t.order('filters.executorSurname.title'),
    placeholder: t.order('filters.executorSurname.placeholder'),
    label: t.order('filters.executorSurname.label'),
    type: 'executorSurname',
  },
  orderIdentifier: {
    title: t.order('filters.orderIdentifier.title'),
    placeholder: t.order('filters.orderIdentifier.placeholder'),
    label: t.order('filters.orderIdentifier.label'),
    type: 'orderIdentifier',
  },
};

const BILLS_FILTERS_LIST = {
  ...SHARED_FILTERS,
  '1cDateFrom': {
    title: t.order('filters.toStartAtDateFrom'),
    placeholder: `от ${moment().format('ll')}`,
    type: '1cDateFrom',
    datePicker: true,
    period: 1,
  },
  '1cDateTill': {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: '1cDateTill',
    datePicker: true,
    period: 2,
  },
  billId: {
    title: t.bills('table.billNumber'),
    placeholder: t.bills('table.billNumber'),
    type: '1cInvoiceId',
    icon: 'searchBlue',
  },
  orderId: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'orderId',
    icon: 'searchBlue',
  },
  paymentState: {
    title: t.bills('payed'),
    label: t.bills('payed'),
    placeholder: t.bills('allCategories'),
    type: 'paymentState',
    dropDownKey: 'invoices',
    dropDown: true,
  },
  status: {
    title: t.bills('table.status'),
    label: t.bills('table.status'),
    placeholder: t.bills('allStatuses'),
    type: 'status',
    dropDown: true,
  },
  invoiceSumMin: {
    title: t.bills('sumFrom'),
    label: t.bills('sumFrom'),
    placeholder: t.bills('sumFrom'),
    type: 'invoiceSumMin',
  },
  invoiceSumMax: {
    title: t.bills('sumTo'),
    label: t.bills('sumTo'),
    placeholder: t.bills('sumTo'),
    type: 'invoiceSumMax',
  },
  producerId: {
    title: t.order('contractor'),
    label: t.order('contractor'),
    placeholder: t.order('contractor'),
    type: 'producerId',
  },
  orderClientIdentifier: {
    title: t.order('orderIdentifier'),
    label: t.order('orderIdentifier'),
    placeholder: t.order('orderIdentifier'),
    type: 'orderClientIdentifier',
  },
};

const DEFERRED_FILTERS_LIST = {
  ...SHARED_FILTERS,
  toStartAtDateFrom: {
    title: t.order('filters.toStartAtDateFrom'),
    placeholder: `от ${moment().format('DD.MM.YYYY')}`,
    type: 'toStartAtDateFrom',
    datePicker: true,
    period: 1,
  },
  toStartAtDateTill: {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('DD.MM.YYYY')}`,
    type: 'toStartAtDateTill',
    datePicker: true,
    period: 2,
  },
  orderId: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'orderId',
    icon: 'searchBlue',
  },
  firstAddress: {
    title: t.order('filters.loadingAddress.title'),
    placeholder: t.order('filters.loadingAddress.placeholder'),
    label: t.order('filters.loadingAddress.label'),
    type: 'firstAddress',
    icon: 'searchBlue',
  },
  vehicleTypeId: {
    type: 'vehicleTypeId',
    placeholder: t.order('vehicleType'),
    title: t.order('vehicleType'),
    label: t.order('vehicleType'),
    icon: 'searchBlue',
  },
};

const AUCTIONS_FILTERS_LIST = {
  ...SHARED_FILTERS,
  toStartAtDateFrom: {
    title: t.order('filters.toStartAtDateFrom'),
    placeholder: `от ${moment().format('ll')}`,
    type: 'toStartAtDateFrom',
    datePicker: true,
    period: 1,
  },
  toStartAtDateTill: {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'toStartAtDateTill',
    datePicker: true,
    period: 2,
  },
  orderId: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'orderId',
    icon: 'searchBlue',
  },
  producerId: {
    title: t.order('contractor'),
    label: t.order('contractor'),
    placeholder: t.order('contractor'),
    type: 'producerId',
    icon: 'searchBlue',
  },
  auctionType: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'auctionType',
    icon: 'searchBlue',
  },
  auctionType2: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'auctionType2',
    icon: 'searchBlue',
  },
};

const TRANSPORTS_FILTER_LIST = {
  id: {
    title: t.registries('ID'),
    placeholder: t.registries('ID'),
    type: 'filterVehicleId',
    icon: 'searchBlue',
  },
  filterVehicleTypeIds: {
    type: 'filterVehicleTypeIds',
    placeholder: t.order('vehicleType'),
    title: t.order('vehicleType'),
    label: t.order('vehicleType'),
    dropDownKey: 'vehicleTypes',
    dropDown: true,
  },
  filterVehicleStates: {
    type: 'filterVehicleStates',
    placeholder: t.transports('Все'),
    title: t.transports('uiStatus'),
    label: t.transports('uiStatus'),
    dropDownKey: 'unitUiStates',
    dropDown: true,
  },
  filterPlateNumber: {
    title: t.order('filters.plateNumber.title'),
    label: t.order('filters.plateNumber.title'),
    placeholder: t.order('filters.plateNumber.placeholder'),
    type: 'filterPlateNumber',
    icon: 'searchBlue',
  },
  filterDriverSurname: {
    type: 'filterDriverSurname',
    title: t.transports('fio'),
    //label: t.transports('fio'),
    placeholder: t.transports('Ф.И.О. водителя'),
    localSearch: true,
    icon: 'searchBlue',
    style: { width: '312px' },
  },
  producer: {
    title: t.loader('filter.producer'),
    label: t.loader('filter.producer'),
    placeholder: t.loader('filter.producer'),
    icon: 'searchBlue',
    type: 'filterProducer',
  },
};

const OPERATOR_TRANSPORTS_FILTER_LIST = {
  id: {
    title: t.registries('ID'),
    placeholder: t.registries('ID'),
    type: 'filterVehicleId',
    icon: 'searchBlue',
  },
  filterVehicleTypeIds: {
    type: 'filterVehicleTypeIds',
    placeholder: t.order('vehicleType'),
    title: t.order('vehicleType'),
    label: t.order('vehicleType'),
    dropDownKey: 'vehicleTypes',
    dropDown: true,
  },
  filterVehicleStates: {
    type: 'filterUiStatus',
    placeholder: t.transports('Все'),
    title: t.transports('uiStatus'),
    label: t.transports('uiStatus'),
    dropDownKey: 'unitUiStates',
    dropDown: true,
  },
  filterPlateNumber: {
    title: t.order('filters.plateNumber.title'),
    label: t.order('filters.plateNumber.title'),
    placeholder: t.order('filters.plateNumber.placeholder'),
    type: 'filterPlateNumber',
    icon: 'searchBlue',
  },
  filterDriverSurname: {
    type: 'filterDriverSurname',
    title: t.transports('fio'),
    //label: t.transports('fio'),
    placeholder: t.transports('Ф.И.О. водителя'),
    localSearch: false,
    icon: 'searchBlue',
    style: { width: '312px' },
  },
  producer: {
    title: t.loader('filter.producer'),
    label: t.loader('filter.producer'),
    placeholder: t.loader('filter.producer'),
    icon: 'searchBlue',
    type: 'filterProducerCompany',
  },
};

const DRIVER_FILTER_LIST = {
  id: {
    title: t.registries('ID'),
    placeholder: t.registries('ID'),
    type: 'filterId',
    icon: 'searchBlue',
  },
  filterSurname: {
    type: 'filterSurname',
    placeholder: t.driver('filters.filterSurname'),
    title: t.driver('filters.filterSurname'),
    label: t.driver('filters.filterSurname'),
    icon: 'searchBlue',
  },
  filterMinRatingByClient: {
    type: 'filterMinRatingByClient',
    placeholder: t.driver('filters.filterMinRatingByClient'),
    title: t.driver('filters.filterMinRatingByClient'),
    label: t.driver('filters.filterMinRatingByClient'),
    dropDown: true,
    dropDownKey: '',
  },
  filterSystemStates: {
    type: 'filterSystemStates',
    placeholder: t.driver('filters.filterSystemStates'),
    title: t.driver('filters.filterSystemStates'),
    label: t.driver('filters.filterSystemStates'),
    dropDown: true,
    dropDownKey: 'unitUiStates',
  },
  filterMobilePhone: {
    type: 'filterMobilePhone',
    placeholder: t.driver('filters.filterMobilePhone'),
    title: t.driver('filters.filterMobilePhone'),
    label: t.driver('filters.filterMobilePhone'),
    icon: 'searchBlue',
  },
  producer: {
    title: t.loader('filter.producer'),
    label: t.loader('filter.producer'),
    placeholder: t.loader('filter.producer'),
    icon: 'searchBlue',
    type: 'filterProducer',
  },
};

const PRODUCER_ORDER_FILTER_LIST = {
  ...SHARED_FILTERS,
  filterStartDateSince: {
    title: t.order('filters.toStartAtDateFrom'),
    placeholder: `от ${moment().format('ll')}`,
    type: 'filterStartDateSince',
    datePicker: true,
    period: 1,
  },
  filterStartDateTill: {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'filterStartDateTill',
    datePicker: true,
    period: 2,
  },
  filterOrderId: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'filterOrderId',
    icon: 'searchBlue',
  },
  filterOrderUiStates: {
    title: t.order('filters.orderStatus.title'),
    label: t.order('filters.orderStatus.label'),
    placeholder: t.order('filters.orderStatus.placeholder'),
    type: 'filterOrderUiStates',
    dropDownKey: 'transportOrderStatuses',
    dropDown: true,
  },
  orderStage: {
    title: t.order('filters.orderStage.title'),
    label: t.order('filters.orderStage.label'),
    placeholder: t.order('filters.orderStage.placeholder'),
    type: 'orderStages',
    dropDownKey: 'orderStages',
    dropDown: true,
  },
  filterOrderType: {
    title: t.order('filters.orderType.title'),
    placeholder: t.order('filters.orderType.placeholder'),
    label: t.order('filters.orderType.label'),
    type: 'filterOrderType',
    dropDownKey: 'orderTypes',
    dropDown: true,
  },
  filterVehicleTypeId: {
    title: t.order('filters.transportType.title'),
    placeholder: t.order('filters.transportType.placeholder'),
    label: t.order('filters.transportType.label'),
    type: 'filterVehicleTypeId',
    dropDownKey: 'vehicleBodyTypes',
    dropDown: true,
  },
  filterVehiclePlateNumber: {
    type: 'filterVehiclePlateNumber',
    title: t.order('filters.plateNumber.title'),
    placeholder: t.order('filters.plateNumber.placeholder'),
    label: t.order('filters.plateNumber.label'),
    icon: 'searchBlue',
  },
  filterSubProducerId: {
    type: 'filterSubProducerId',
    title: t.order('filters.filterSubProducerId.title'),
    placeholder: t.order('filters.filterSubProducerId.placeholder'),
    label: t.order('filters.filterSubProducerId.label'),
    icon: 'searchBlue',
  },
  filterActNo: {
    title: t.order('filters.actNo.title'),
    placeholder: t.order('filters.actNo.placeholder'),
    label: t.order('filters.actNo.label'),
    type: 'filterActNo',
    icon: 'searchBlue',
  },
  filterClientName: {
    title: t.order('filters.filterClientName.title'),
    placeholder: t.order('filters.filterClientName.placeholder'),
    label: t.order('filters.filterClientName.label'),
    type: 'filterClientName',
    icon: 'searchBlue',
  },
  filterTotalSumInCents: {
    title: t.order('filters.totalSumInCents.title'),
    placeholder: t.order('filters.totalSumInCents.placeholder'),
    label: t.order('filters.totalSumInCents.label'),
    type: 'filterTotalSumInCents',
    icon: 'searchBlue',
  },
  finishDateSince: {
    title: t.order('filters.finishedAtDate.title'),
    label: t.order('filters.finishedAtDate.label'),
    type: 'filterFinishDateSince',
    placeholder: `от ${moment().format('ll')}`,
    datePicker: true,
    combinedWith: {
      type: 'filterFinishDateTill',
      title: t.order('filters.finishedAtDateSince.title'),
      label: t.order('filters.finishedAtDateSince.label'),
      placeholder: `от ${moment().format('ll')}`,
      datePicker: true,
    },
  },
  filterLastAddress: {
    title: t.order('filters.filterLastAddress.title'),
    placeholder: t.order('filters.filterLastAddress.placeholder'),
    label: t.order('filters.filterLastAddress.label'),
    type: 'filterLastAddress',
    icon: 'searchBlue',
  },
  filterFirstAddress: {
    title: t.order('filters.filterFirstAddress.title'),
    placeholder: t.order('filters.filterFirstAddress.placeholder'),
    label: t.order('filters.filterFirstAddress.label'),
    type: 'filterFirstAddress',
    icon: 'searchBlue',
  },
  filterOrderProducerCustomIdentifier: {
    title: t.order('filters.filterOrderProducerCustomIdentifier.title'),
    placeholder: t.order('filters.filterOrderProducerCustomIdentifier.placeholder'),
    label: t.order('filters.filterOrderProducerCustomIdentifier.label'),
    type: 'filterOrderProducerCustomIdentifier',
    icon: 'searchBlue',
  },
};

const OPERATOR_ORDER_FILTER_LIST = {
  ...SHARED_FILTERS,
  filterStartDateSince: {
    title: t.order('filters.toStartAtDateFrom'),
    placeholder: `от ${moment().format('ll')}`,
    type: 'filterToStartDateSince',
    datePicker: true,
    period: 1,
  },
  filterStartDateTill: {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'filterToStartDateTill',
    datePicker: true,
    period: 2,
  },
  filterOrderId: {
    title: t.order('filters.orderId.title'),
    placeholder: t.order('filters.orderId.placeholder'),
    type: 'filterOrderId',
    icon: 'searchBlue',
  },
  filterOrderUiStates: {
    title: t.order('filters.orderStatus.title'),
    label: t.order('filters.orderStatus.label'),
    placeholder: t.order('filters.orderStatus.placeholder'),
    type: 'filterOrderUiState',
    dropDownKey: 'transportOrderStatuses',
    dropDown: true,
  },
  orderStage: {
    title: t.order('filters.orderStage.title'),
    label: t.order('filters.orderStage.label'),
    placeholder: t.order('filters.orderStage.placeholder'),
    type: 'orderStages',
    dropDownKey: 'orderStages',
    dropDown: true,
  },
  filterOrderType: {
    title: t.order('filters.orderType.title'),
    placeholder: t.order('filters.orderType.placeholder'),
    label: t.order('filters.orderType.label'),
    type: 'filterOrderType',
    dropDownKey: 'orderTypes',
    dropDown: true,
  },
  filterVehicleTypeId: {
    title: t.order('filters.transportType.title'),
    placeholder: t.order('filters.transportType.placeholder'),
    label: t.order('filters.transportType.label'),
    type: 'filterVehicleTypeId',
    dropDownKey: 'vehicleBodyTypes',
    dropDown: true,
  },
  filterVehiclePlateNumber: {
    type: 'filterVehiclePlateNumber',
    title: t.order('filters.plateNumber.title'),
    placeholder: t.order('filters.plateNumber.placeholder'),
    label: t.order('filters.plateNumber.label'),
    icon: 'searchBlue',
  },
  filterSubProducerId: {
    type: 'filterSubProducerId',
    title: t.order('filters.filterSubProducerId.title'),
    placeholder: t.order('filters.filterSubProducerId.placeholder'),
    label: t.order('filters.filterSubProducerId.label'),
    icon: 'searchBlue',
  },
  filterActNo: {
    title: t.order('filters.actNo.title'),
    placeholder: t.order('filters.actNo.placeholder'),
    label: t.order('filters.actNo.label'),
    type: 'filterActNo',
    icon: 'searchBlue',
  },
  filterClientCompany: {
    title: t.order('filters.filterClientName.title'),
    placeholder: t.order('filters.filterClientName.placeholder'),
    label: t.order('filters.filterClientName.label'),
    type: 'filterClientCompany',
    icon: 'searchBlue',
  },
  filterProducerCompany: {
    title: t.order('filters.filterProducerName.title'),
    placeholder: t.order('filters.filterProducerName.placeholder'),
    label: t.order('filters.filterProducerName.label'),
    type: 'filterProducerCompany',
    icon: 'searchBlue',
  },
  filterTotalSumInCents: {
    title: t.order('filters.totalSumInCents.title'),
    placeholder: t.order('filters.totalSumInCents.placeholder'),
    label: t.order('filters.totalSumInCents.label'),
    type: 'filterTotalSumInCents',
    icon: 'searchBlue',
  },
  finishDateSince: {
    title: t.order('filters.finishedAtDate.title'),
    label: t.order('filters.finishedAtDate.label'),
    type: 'filterFinishDateSince',
    placeholder: `от ${moment().format('ll')}`,
    datePicker: true,
    combinedWith: {
      type: 'filterFinishDateTill',
      title: t.order('filters.finishedAtDateSince.title'),
      label: t.order('filters.finishedAtDateSince.label'),
      placeholder: `от ${moment().format('ll')}`,
      datePicker: true,
    },
  },
  filterLastAddress: {
    title: t.order('filters.filterLastAddress.title'),
    placeholder: t.order('filters.filterLastAddress.placeholder'),
    label: t.order('filters.filterLastAddress.label'),
    type: 'filterLastAddress',
    icon: 'searchBlue',
  },
  filterFirstAddress: {
    title: t.order('filters.filterFirstAddress.title'),
    placeholder: t.order('filters.filterFirstAddress.placeholder'),
    label: t.order('filters.filterFirstAddress.label'),
    type: 'filterFirstAddress',
    icon: 'searchBlue',
  },
  filterOrderProducerCustomIdentifier: {
    title: t.order('filters.filterOrderProducerCustomIdentifier.title'),
    placeholder: t.order('filters.filterOrderProducerCustomIdentifier.placeholder'),
    label: t.order('filters.filterOrderProducerCustomIdentifier.label'),
    type: 'filterOrderProducerCustomIdentifier',
    icon: 'searchBlue',
  },
};

const TRACTORS_FILTER_LIST = {
  status: {
    title: t.order('filters.orderStatus.title'),
    label: t.order('filters.orderStatus.label'),
    placeholder: t.order('filters.orderStatus.placeholder'),
    type: 'status',
    dropDownKey: 'unitUiStates',
    dropDown: true,
  },
  plateNumber: {
    type: 'plateNumber',
    title: t.order('filters.plateNumber.title'),
    placeholder: t.order('filters.plateNumber.placeholder'),
    label: t.order('filters.plateNumber.label'),
    icon: 'searchBlue',
  },
};

const REGISTRIES_FILTER_LIST = {
  ...SHARED_FILTERS,
  paymentState: {
    title: t.registries('payment'),
    label: t.registries('payment'),
    type: 'paymentState',
    dropDownKey: 'invoicesPaymentStatuses',
    dropDown: true,
    placeholder: t.registries('all'),
  },
  id: {
    title: t.registries('table.id'),
    placeholder: t.registries('table.id'),
    type: 'id',
    icon: 'searchBlue',
  },
  act1cId: {
    title: t.registries('actNumber'),
    placeholder: t.registries('actNumber'),
    type: 'act1cId',
    icon: 'searchBlue',
  },
  orderId: {
    title: t.registries('orderId'),
    placeholder: t.registries('orderId'),
    type: 'orderId',
    icon: 'searchBlue',
  },
  date1cFrom: {
    title: t.registries('actDates'),
    type: 'date1cFrom',
    placeholder: `от ${moment().subtract(1, 'months').format('ll')}`,
    datePicker: true,
    period: 1,
  },
  date1cTill: {
    type: 'date1cTill',
    placeholder: `до ${moment().format('ll')}`,
    datePicker: true,
    period: 2,
  },
  clientTitle: {
    type: 'clientTitle',
    title: t.registries('filters.clientTitle'),
    placeholder: t.registries('filters.clientTitle'),
    icon: 'searchBlue',
  },
  renterName: {
    type: 'renterName',
    title: t.registries('filters.renterName'),
    placeholder: t.registries('filters.renterName'),
    icon: 'searchBlue',
  },
  producerOrderIdentifier: {
    type: 'producerOrderIdentifier',
    title: t.registries('filters.producerOrderIdentifier'),
    placeholder: t.registries('filters.producerOrderIdentifier'),
    icon: 'searchBlue',
  },
  payedDateFrom: {
    type: 'payedDateFrom',
    title: t.registries('filters.payedDateTill'),
    label: t.registries('filters.payedDateTill'),
    placeholder: `от ${moment().format('ll')}`,
    datePicker: true,
    combinedWith: {
      type: 'payedDateTill',
      title: t.registries('filters.to'),
      label: t.registries('filters.to'),
      placeholder: `до ${moment().format('ll')}`,
      datePicker: true,
    },
  },
  registrySumFrom: {
    type: 'registrySumFrom',
    title: t.registries('filters.registrySumFrom'),
    label: t.registries('filters.registrySumFrom'),
    placeholder: t.registries('filters.from'),
    combinedWith: {
      type: 'registrySumTill',
      placeholder: t.registries('filters.to'),
    },
  },
};

const CARTULARY_FILTER_LIST = {
  ...SHARED_FILTERS,
  typeCartulary: {
    title: t.cartulary('typeCartulary'),
    label: t.cartulary('typeCartulary'),
    type: 'filterOrderType',
    dropDownKey: 'orderType',
    dropDown: true,
    placeholder: t.cartulary('all'),
  },
  filterStartDateSince: {
    title: t.cartulary('filters.toStartAtDateFrom'),
    type: 'filterStartDateSince',
    placeholder: `от ${moment().format('ll')}`,
    datePicker: true,
    period: 1,
  },
  filterStartDateTill: {
    title: t.cartulary('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'filterStartDateTill',
    datePicker: true,
    period: 1,
  },
  orderId: {
    title: t.cartulary('orderId'),
    placeholder: t.cartulary('orderId'),
    type: 'filterOrderId',
    icon: 'searchBlue',
  },
  clientTitle: {
    type: 'filterClientCompany',
    title: t.cartulary('filters.clientTitle'),
    label: t.cartulary('filters.clientTitle'),
    placeholder: t.cartulary('filters.clientTitle'),
    icon: 'searchBlue',
  },
  renterName: {
    type: 'filterProducerCompany',
    title: t.cartulary('filters.renterName'),
    label: t.cartulary('filters.renterName'),
    placeholder: t.cartulary('filters.renterName'),
    icon: 'searchBlue',
  },
};

const DOCUMENTS_FILTER_LIST = {
  ...SHARED_FILTERS,
  filterStartDateSince: {
    title: t.order('filters.toStartAtDateFrom'),
    type: 'filterStartDateSince',
    placeholder: `от ${moment().format('ll')}`,
    datePicker: true,
    period: 1,
  },
  filterStartDateTill: {
    title: t.order('filters.toStartAtDateTill'),
    placeholder: `до ${moment().format('ll')}`,
    type: 'filterStartDateTill',
    datePicker: true,
    period: 1,
  },
  orderId: {
    title: t.documents('filters.orderId'),
    placeholder: t.documents('filters.orderId'),
    type: 'orderId',
    icon: 'searchBlue',
  },
  driverFIO: {
    title: t.documents('filters.driverFIO'),
    placeholder: t.documents('filters.driverFIO'),
    type: 'driverFIO',
    icon: 'searchBlue',
  },
  vehiclePlateNumber: {
    title: t.documents('filters.vehiclePlateNumber'),
    placeholder: t.documents('filters.vehiclePlateNumber'),
    type: 'vehiclePlateNumber',
    icon: 'searchBlue',
  },
};

const TRAILERS_FILTER_LIST = {
  plateNumber: {
    title: t.documents('filters.vehiclePlateNumber'),
    placeholder: t.documents('filters.vehiclePlateNumber'),
    type: 'plateNumber',
    icon: 'searchBlue',
  },
  status: {
    title: t.trailer('filters.status'),
    label: t.trailer('filters.status'),
    placeholder: t.trailer('filters.status'),
    type: 'status',
    dropDown: true,
    dropDownKey: 'unitUiStates',
  },
};

const LOADERS_FILTER_LIST = {
  fio: {
    title: t.loader('filter.fio'),
    label: t.loader('filter.fio'),
    placeholder: t.loader('filter.fio'),
    icon: 'searchBlue',
    type: 'filterSurname',
  },
  producer: {
    title: t.loader('filter.producer'),
    label: t.loader('filter.producer'),
    placeholder: t.loader('filter.producer'),
    icon: 'searchBlue',
    type: 'filterProducer',
  },
  filterMinRatingByClient: {
    type: 'filterMinRatingByClient',
    placeholder: t.driver('filters.filterMinRatingByClient'),
    title: t.driver('filters.filterMinRatingByClient'),
    label: t.driver('filters.filterMinRatingByClient'),
    dropDown: true,
    dropDownKey: '',
  },
  filterSystemStates: {
    title: t.loader('filter.filterSystemStates'),
    label: t.loader('filter.filterSystemStates'),
    placeholder: t.loader('filter.filterSystemStates'),
    type: 'filterSystemStates',
    dropDownKey: 'employeeSystemStates',
    dropDown: true,
  },
  filterMobilePhone: {
    title: t.loader('filter.filterMobilePhone'),
    label: t.loader('filter.filterMobilePhone'),
    placeholder: t.loader('filter.filterMobilePhone'),
    type: 'filterMobilePhone',
    icon: 'searchBlue',
  },
  filterProducerId: {
    title: t.loader('filter.filterProducerId'),
    label: t.loader('filter.filterProducerId'),
    placeholder: t.loader('filter.filterProducerId'),
    type: 'filterProducerId',
    icon: 'searchBlue',
  },
};

const CLIENTS_FILTER_LIST = {
  filterClientsId: {
    title: t.clients('filter.id'),
    placeholder: t.clients('filter.id'),
    icon: 'searchBlue',
    type: 'filterId',
  },
  filterClientsName: {
    title: t.clients('filter.filterName'),
    label: t.clients('filter.filterName'),
    placeholder: t.clients('filter.all'),
    type: 'filterName',
  },
  filterBalance: {
    title: t.clients('filter.filterMinBalance'),
    label: t.clients('filter.filterMinBalance'),
    placeholder: '',
    type: 'filterMinBalance',
  },
  filterInn: {
    title: t.clients('filter.filterInn'),
    label: t.clients('filter.filterInn'),
    placeholder: '',
    type: 'filterInn',
  },
  filterStates: {
    type: 'filterStates',
    placeholder: t.transports('Все'),
    title: t.transports('uiStatus'),
    label: t.transports('uiStatus'),
    dropDownKey: 'contractorStates',
    dropDown: true,
  },
};

const PRODUCER_FILTER_LIST = {
  filterClientsId: {
    title: t.clients('filter.id'),
    placeholder: t.clients('filter.id'),
    icon: 'searchBlue',
    type: 'filterId',
  },
  filterClientsName: {
    title: t.clients('filter.filterName'),
    label: t.clients('filter.filterName'),
    placeholder: t.clients('filter.all'),
    type: 'filterName',
  },
  filterBalance: {
    title: t.clients('filter.filterMinBalance'),
    label: t.clients('filter.filterMinBalance'),
    placeholder: '',
    type: 'filterMinBalance',
  },
  filterInn: {
    title: t.clients('filter.filterInn'),
    label: t.clients('filter.filterInn'),
    placeholder: '',
    type: 'filterInn',
  },
  filterStates: {
    type: 'filterStates',
    placeholder: t.transports('Все'),
    title: t.transports('uiStatus'),
    label: t.transports('uiStatus'),
    dropDownKey: 'contractorStates',
    dropDown: true,
  },
};

const OPERATOR_DRIVER_FILTER_LIST = {
  id: {
    title: t.registries('ID'),
    placeholder: t.registries('ID'),
    type: 'filterId',
    icon: 'searchBlue',
  },
  filterSurname: {
    type: 'filterSurname',
    placeholder: t.driver('filters.filterSurname'),
    title: t.driver('filters.filterSurname'),
    label: t.driver('filters.filterSurname'),
    icon: 'searchBlue',
  },
  filterMinRatingByClient: {
    type: 'filterMinRatingByClient',
    placeholder: t.driver('filters.filterMinRatingByClient'),
    title: t.driver('filters.filterMinRatingByClient'),
    label: t.driver('filters.filterMinRatingByClient'),
    dropDown: true,
    dropDownKey: '',
  },
  filterSystemStates: {
    type: 'filterSystemStates',
    placeholder: t.driver('filters.filterSystemStates'),
    title: t.driver('filters.filterSystemStates'),
    label: t.driver('filters.filterSystemStates'),
    dropDown: true,
    dropDownKey: 'unitUiStates',
  },
  filterMobilePhone: {
    type: 'filterMobilePhone',
    placeholder: t.driver('filters.filterMobilePhone'),
    title: t.driver('filters.filterMobilePhone'),
    label: t.driver('filters.filterMobilePhone'),
    icon: 'searchBlue',
  },
  filterProducerCompany: {
    title: t.loader('filter.producer'),
    label: t.loader('filter.producer'),
    placeholder: t.loader('filter.producer'),
    icon: 'searchBlue',
    type: 'filterProducerCompany',
  },
};

export {
  FILTERS_LIST,
  BILLS_FILTERS_LIST,
  DEFERRED_FILTERS_LIST,
  AUCTIONS_FILTERS_LIST,
  TRANSPORTS_FILTER_LIST,
  DRIVER_FILTER_LIST,
  PRODUCER_ORDER_FILTER_LIST,
  OPERATOR_ORDER_FILTER_LIST,
  TRACTORS_FILTER_LIST,
  REGISTRIES_FILTER_LIST,
  CARTULARY_FILTER_LIST,
  DOCUMENTS_FILTER_LIST,
  TRAILERS_FILTER_LIST,
  LOADERS_FILTER_LIST,
  CLIENTS_FILTER_LIST,
  PRODUCER_FILTER_LIST,
  OPERATOR_TRANSPORTS_FILTER_LIST,
  OPERATOR_DRIVER_FILTER_LIST,
};
